version: "3.5"

services:
  manytomany-app:
    build: .
    ports:
      - "8889:80"
    volumes:
      - ./:/var/www
    networks:
      - manytomany-network
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
  manytomanydb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: manytomany
      MYSQL_USER: manytomany
      MYSQL_PASSWORD: manytomany123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - manytomany-network
networks:
  manytomany-network:
    driver: bridge
